export const slidedata = [
    {
        id:1,
        url:"https://i.ibb.co/D1LyGP2/lunch.jpg"
    },
    {
        id:2,
        url:"https://i.ibb.co/591Bsp5/bf.jpg"
    },
    {
        id:3,
        url:"https://i.ibb.co/JnN3cq9/Nice-looking-attractive-gorgeous-glamorous-elegant-stylish-cheerful-cheery-positive-girls-and-guys-h.jpg"
    },
    {
        id:4,
        url:"https://i.ibb.co/QcfjzzX/drinks2.jpg"
    },
    {
        id:5,
        url:"https://i.ibb.co/fdqYvPR/snacks-Meal.jpg"
    },
    {
        id:6,
        url:"https://i.ibb.co/R6KHXzH/dinner.jpg"
    },
    {
        id:7,
        url:"https://i.ibb.co/f0CpLBc/delivery-removebg-preview.png"
    },
    {
        id:8,
        url:"https://i.ibb.co/z7mQp0G/Party-food-assortment-of-salty-snacks-in-bowls-shot-on-white-background-High-angle-view-Predominant.jpg"
    }
]

export const carousaldata = [
    {
        id:1,
        url:"https://i.ibb.co/FgntDBL/image-search-1639242746269.png"
    },
    {
        id:2,
        url:"https://i.ibb.co/ZJR0VLD/image-search-1639242742867.png"
    },
    {
        id:3,
        url:"https://i.ibb.co/nLjdMzb/image-search-1639762897209.png"
    }
]